//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.22 at 08:05:26 AM BRT 
//


package br.com.gft.testautomation.common.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RssChannelItemDescriptionPBr_QNAME = new QName("", "br");
    private final static QName _RssChannelItemAttachmentsAttachment_QNAME = new QName("", "attachment");
    private final static QName _RssChannelItemCommentsCommentUlLiB_QNAME = new QName("", "b");
    private final static QName _RssChannelItemDescriptionUlLi_QNAME = new QName("", "li");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Rss }
     * 
     */
    public Rss createRss() {
        return new Rss();
    }

    /**
     * Create an instance of {@link Rss.Channel }
     * 
     */
    public Rss.Channel createRssChannel() {
        return new Rss.Channel();
    }

    /**
     * Create an instance of {@link Rss.Channel.Item }
     * 
     */
    public Rss.Channel.Item createRssChannelItem() {
        return new Rss.Channel.Item();
    }

    /**
     * Create an instance of {@link Rss.Channel.Item.Customfields }
     * 
     */
    public Rss.Channel.Item.Customfields createRssChannelItemCustomfields() {
        return new Rss.Channel.Item.Customfields();
    }

    /**
     * Create an instance of {@link Rss.Channel.Item.Customfields.Customfield }
     * 
     */
    public Rss.Channel.Item.Customfields.Customfield createRssChannelItemCustomfieldsCustomfield() {
        return new Rss.Channel.Item.Customfields.Customfield();
    }

    /**
     * Create an instance of {@link Rss.Channel.Item.Customfields.Customfield.Customfieldvalues }
     * 
     */
    public Rss.Channel.Item.Customfields.Customfield.Customfieldvalues createRssChannelItemCustomfieldsCustomfieldCustomfieldvalues() {
        return new Rss.Channel.Item.Customfields.Customfield.Customfieldvalues();
    }

    /**
     * Create an instance of {@link Rss.Channel.Item.Attachments }
     * 
     */
    public Rss.Channel.Item.Attachments createRssChannelItemAttachments() {
        return new Rss.Channel.Item.Attachments();
    }

    /**
     * Create an instance of {@link Rss.Channel.Item.Comments }
     * 
     */
    public Rss.Channel.Item.Comments createRssChannelItemComments() {
        return new Rss.Channel.Item.Comments();
    }

    /**
     * Create an instance of {@link Rss.Channel.Item.Comments.Comment }
     * 
     */
    public Rss.Channel.Item.Comments.Comment createRssChannelItemCommentsComment() {
        return new Rss.Channel.Item.Comments.Comment();
    }

    /**
     * Create an instance of {@link Rss.Channel.Item.Comments.Comment.Ul }
     * 
     */
    public Rss.Channel.Item.Comments.Comment.Ul createRssChannelItemCommentsCommentUl() {
        return new Rss.Channel.Item.Comments.Comment.Ul();
    }

    /**
     * Create an instance of {@link Rss.Channel.Item.Description }
     * 
     */
    public Rss.Channel.Item.Description createRssChannelItemDescription() {
        return new Rss.Channel.Item.Description();
    }

    /**
     * Create an instance of {@link Rss.Channel.Issue }
     * 
     */
    public Rss.Channel.Issue createRssChannelIssue() {
        return new Rss.Channel.Issue();
    }

    /**
     * Create an instance of {@link Rss.Channel.BuildInfo }
     * 
     */
    public Rss.Channel.BuildInfo createRssChannelBuildInfo() {
        return new Rss.Channel.BuildInfo();
    }

    /**
     * Create an instance of {@link Rss.Channel.Item.Project }
     * 
     */
    public Rss.Channel.Item.Project createRssChannelItemProject() {
        return new Rss.Channel.Item.Project();
    }

    /**
     * Create an instance of {@link Rss.Channel.Item.Key }
     * 
     */
    public Rss.Channel.Item.Key createRssChannelItemKey() {
        return new Rss.Channel.Item.Key();
    }

    /**
     * Create an instance of {@link Rss.Channel.Item.Type }
     * 
     */
    public Rss.Channel.Item.Type createRssChannelItemType() {
        return new Rss.Channel.Item.Type();
    }

    /**
     * Create an instance of {@link Rss.Channel.Item.Priority }
     * 
     */
    public Rss.Channel.Item.Priority createRssChannelItemPriority() {
        return new Rss.Channel.Item.Priority();
    }

    /**
     * Create an instance of {@link Rss.Channel.Item.Status }
     * 
     */
    public Rss.Channel.Item.Status createRssChannelItemStatus() {
        return new Rss.Channel.Item.Status();
    }

    /**
     * Create an instance of {@link Rss.Channel.Item.StatusCategory }
     * 
     */
    public Rss.Channel.Item.StatusCategory createRssChannelItemStatusCategory() {
        return new Rss.Channel.Item.StatusCategory();
    }

    /**
     * Create an instance of {@link Rss.Channel.Item.Resolution }
     * 
     */
    public Rss.Channel.Item.Resolution createRssChannelItemResolution() {
        return new Rss.Channel.Item.Resolution();
    }

    /**
     * Create an instance of {@link Rss.Channel.Item.Assignee }
     * 
     */
    public Rss.Channel.Item.Assignee createRssChannelItemAssignee() {
        return new Rss.Channel.Item.Assignee();
    }

    /**
     * Create an instance of {@link Rss.Channel.Item.Reporter }
     * 
     */
    public Rss.Channel.Item.Reporter createRssChannelItemReporter() {
        return new Rss.Channel.Item.Reporter();
    }

    /**
     * Create an instance of {@link Rss.Channel.Item.Timeoriginalestimate }
     * 
     */
    public Rss.Channel.Item.Timeoriginalestimate createRssChannelItemTimeoriginalestimate() {
        return new Rss.Channel.Item.Timeoriginalestimate();
    }

    /**
     * Create an instance of {@link Rss.Channel.Item.Timeestimate }
     * 
     */
    public Rss.Channel.Item.Timeestimate createRssChannelItemTimeestimate() {
        return new Rss.Channel.Item.Timeestimate();
    }

    /**
     * Create an instance of {@link Rss.Channel.Item.Timespent }
     * 
     */
    public Rss.Channel.Item.Timespent createRssChannelItemTimespent() {
        return new Rss.Channel.Item.Timespent();
    }

    /**
     * Create an instance of {@link Rss.Channel.Item.Customfields.Customfield.Customfieldvalues.Customfieldvalue }
     * 
     */
    public Rss.Channel.Item.Customfields.Customfield.Customfieldvalues.Customfieldvalue createRssChannelItemCustomfieldsCustomfieldCustomfieldvaluesCustomfieldvalue() {
        return new Rss.Channel.Item.Customfields.Customfield.Customfieldvalues.Customfieldvalue();
    }

    /**
     * Create an instance of {@link Rss.Channel.Item.Attachments.Attachment }
     * 
     */
    public Rss.Channel.Item.Attachments.Attachment createRssChannelItemAttachmentsAttachment() {
        return new Rss.Channel.Item.Attachments.Attachment();
    }

    /**
     * Create an instance of {@link Rss.Channel.Item.Comments.Comment.P }
     * 
     */
    public Rss.Channel.Item.Comments.Comment.P createRssChannelItemCommentsCommentP() {
        return new Rss.Channel.Item.Comments.Comment.P();
    }

    /**
     * Create an instance of {@link Rss.Channel.Item.Comments.Comment.Ul.Li }
     * 
     */
    public Rss.Channel.Item.Comments.Comment.Ul.Li createRssChannelItemCommentsCommentUlLi() {
        return new Rss.Channel.Item.Comments.Comment.Ul.Li();
    }

    /**
     * Create an instance of {@link Rss.Channel.Item.Description.P }
     * 
     */
    public Rss.Channel.Item.Description.P createRssChannelItemDescriptionP() {
        return new Rss.Channel.Item.Description.P();
    }

    /**
     * Create an instance of {@link Rss.Channel.Item.Description.Ul }
     * 
     */
    public Rss.Channel.Item.Description.Ul createRssChannelItemDescriptionUl() {
        return new Rss.Channel.Item.Description.Ul();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "br", scope = Rss.Channel.Item.Description.P.class)
    public JAXBElement<String> createRssChannelItemDescriptionPBr(String value) {
        return new JAXBElement<String>(_RssChannelItemDescriptionPBr_QNAME, String.class, Rss.Channel.Item.Description.P.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Rss.Channel.Item.Attachments.Attachment }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "attachment", scope = Rss.Channel.Item.Attachments.class)
    public JAXBElement<Rss.Channel.Item.Attachments.Attachment> createRssChannelItemAttachmentsAttachment(Rss.Channel.Item.Attachments.Attachment value) {
        return new JAXBElement<Rss.Channel.Item.Attachments.Attachment>(_RssChannelItemAttachmentsAttachment_QNAME, Rss.Channel.Item.Attachments.Attachment.class, Rss.Channel.Item.Attachments.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "b", scope = Rss.Channel.Item.Comments.Comment.Ul.Li.class)
    public JAXBElement<String> createRssChannelItemCommentsCommentUlLiB(String value) {
        return new JAXBElement<String>(_RssChannelItemCommentsCommentUlLiB_QNAME, String.class, Rss.Channel.Item.Comments.Comment.Ul.Li.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "br", scope = Rss.Channel.Item.Description.Ul.class)
    public JAXBElement<String> createRssChannelItemDescriptionUlBr(String value) {
        return new JAXBElement<String>(_RssChannelItemDescriptionPBr_QNAME, String.class, Rss.Channel.Item.Description.Ul.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "li", scope = Rss.Channel.Item.Description.Ul.class)
    public JAXBElement<String> createRssChannelItemDescriptionUlLi(String value) {
        return new JAXBElement<String>(_RssChannelItemDescriptionUlLi_QNAME, String.class, Rss.Channel.Item.Description.Ul.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "br", scope = Rss.Channel.Item.Comments.Comment.P.class)
    public JAXBElement<String> createRssChannelItemCommentsCommentPBr(String value) {
        return new JAXBElement<String>(_RssChannelItemDescriptionPBr_QNAME, String.class, Rss.Channel.Item.Comments.Comment.P.class, value);
    }

}
